import type { DashboardRespuesta, TiendaRespuesta } from '@pickbros/types';

export const dashboardMock: DashboardRespuesta = {
  usuario: {
    nombre: 'Jairo',
    saludo: '¿Qué onda, Jairo! 👋',
  },
  rango: {
    nombre: 'Pick Master',
    nivel: 23,
  },
  pickCoins: 2450,
  pickets: 12,
  rachaDias: 7,
  challengeDelDia: {
    titulo: 'Pick Challenge del día',
    pregunta: '¿Quién gana este duelo de MLB?',
    local: { nombre: 'Yankees', iniciales: 'NYY', acento: '#2EA8FF' },
    visitante: { nombre: 'Red Sox', iniciales: 'BOS', acento: '#FF6A1A' },
    horario: 'Próximo partido',
    premioPickCoins: 150,
  },
  eventosDestacados: [
    {
      id: 'mlb-1',
      liga: 'MLB',
      local: 'Yankees',
      visitante: 'Red Sox',
      inicialesLocal: 'NYY',
      inicialesVisitante: 'BOS',
      horario: '4:05 PM',
    },
    {
      id: 'nba-1',
      liga: 'NBA',
      local: 'Lakers',
      visitante: 'Nuggets',
      inicialesLocal: 'LAL',
      inicialesVisitante: 'DEN',
      horario: '8:30 PM',
    },
    {
      id: 'nfl-1',
      liga: 'NFL',
      local: 'Chiefs',
      visitante: 'Bengals',
      inicialesLocal: 'KC',
      inicialesVisitante: 'CIN',
      horario: '7:15 PM',
    },
    {
      id: 'ucl-1',
      liga: 'Champions',
      local: 'Real Madrid',
      visitante: 'Dortmund',
      inicialesLocal: 'RMA',
      inicialesVisitante: 'BVB',
      horario: '2:00 PM',
    },
  ],
  rankingSemanal: [
    { puesto: 1, alias: 'Fer007', puntos: 1840 },
    { puesto: 2, alias: 'SportsFanMX', puntos: 1712 },
    { puesto: 3, alias: 'GreenPicks', puntos: 1654 },
    { puesto: 4, alias: 'JairoMX', puntos: 1580, esUsuarioActual: true },
  ],
  misiones: [
    {
      id: 'm1',
      titulo: 'Haz 1 pick del día',
      descripcion: 'Elige un ganador en el challenge de hoy.',
      progreso: 0,
      meta: 1,
    },
    {
      id: 'm2',
      titulo: 'Lee 1 análisis',
      descripcion: 'Entra a un análisis antes del partido.',
      progreso: 1,
      meta: 1,
    },
    {
      id: 'm3',
      titulo: 'Mantén tu racha',
      descripcion: 'No rompas los 7 días seguidos.',
      progreso: 7,
      meta: 7,
    },
    {
      id: 'm4',
      titulo: 'Comparte 1 pick',
      descripcion: 'Mándalo a la comunidad PickBros.',
      progreso: 0,
      meta: 1,
    },
  ],
};

export const tiendaMock: TiendaRespuesta = {
  usuario: dashboardMock.usuario,
  rango: dashboardMock.rango,
  pickCoins: dashboardMock.pickCoins,
  pickets: dashboardMock.pickets,
  rachaDias: dashboardMock.rachaDias,
  productoDestacado: {
    id: 'destacado-hoodie',
    nombre: 'Hoodie Midnight PickBros',
    descripcion: 'Edición navy con glow eléctrico. Mock de merch, sin compra real.',
    categoria: 'merch',
    precioPickets: 8,
    destacado: true,
    etiqueta: 'Destacado de la semana',
  },
  productos: [
    {
      id: 'gorra-navy',
      nombre: 'Gorra Navy Volt',
      descripcion: 'Ajuste clásico, parche PB.',
      categoria: 'fan-shop',
      precioPickets: 3,
      etiqueta: 'Fan Shop',
    },
    {
      id: 'boost-analisis',
      nombre: 'Boost de análisis',
      descripcion: 'Desbloquea 3 lecturas extra por 24 h.',
      categoria: 'recompensas',
      precioPickCoins: 400,
      etiqueta: 'Recompensa',
    },
    {
      id: 'paset-pro-dia',
      nombre: 'Pase Pro de 1 día',
      descripcion: 'Prueba PickBros Pro sin compromiso.',
      categoria: 'premios-exclusivos',
      precioPickets: 5,
      etiqueta: 'Exclusivo',
    },
    {
      id: 'playera-naranja',
      nombre: 'Playera Strike Orange',
      descripcion: 'Algodón pesado, logo centrado.',
      categoria: 'merch',
      precioPickets: 6,
      etiqueta: 'Merch',
    },
    {
      id: 'sticker-pack',
      nombre: 'Pack de stickers PB',
      descripcion: '6 stickers para termo o laptop.',
      categoria: 'fan-shop',
      precioPickCoins: 120,
      etiqueta: 'Fan Shop',
    },
    {
      id: 'double-coins',
      nombre: 'Doble PickCoins',
      descripcion: 'Multiplica tu premio del challenge.',
      categoria: 'recompensas',
      precioPickets: 2,
      etiqueta: 'Recompensa',
    },
  ],
};
