export interface PaisOpcion {
  codigo: string;
  nombre: string;
}

export const PAISES: PaisOpcion[] = [
  { codigo: 'MX', nombre: 'México' },
  { codigo: 'US', nombre: 'Estados Unidos' },
  { codigo: 'CA', nombre: 'Canadá' },
  { codigo: 'AR', nombre: 'Argentina' },
  { codigo: 'CO', nombre: 'Colombia' },
  { codigo: 'ES', nombre: 'España' },
];

export const ESTADOS_POR_PAIS: Record<string, string[]> = {
  MX: [
    'Aguascalientes',
    'Baja California',
    'Baja California Sur',
    'Campeche',
    'Chiapas',
    'Chihuahua',
    'Ciudad de México',
    'Coahuila',
    'Colima',
    'Durango',
    'Estado de México',
    'Guanajuato',
    'Guerrero',
    'Hidalgo',
    'Jalisco',
    'Michoacán',
    'Morelos',
    'Nayarit',
    'Nuevo León',
    'Oaxaca',
    'Puebla',
    'Querétaro',
    'Quintana Roo',
    'San Luis Potosí',
    'Sinaloa',
    'Sonora',
    'Tabasco',
    'Tamaulipas',
    'Tlaxcala',
    'Veracruz',
    'Yucatán',
    'Zacatecas',
  ],
  US: [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Carolina del Norte',
    'Carolina del Sur',
    'Colorado',
    'Connecticut',
    'Dakota del Norte',
    'Dakota del Sur',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawái',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Luisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Míchigan',
    'Minnesota',
    'Misisipi',
    'Misuri',
    'Montana',
    'Nebraska',
    'Nevada',
    'Nueva Jersey',
    'Nueva York',
    'Nuevo Hampshire',
    'Nuevo México',
    'Ohio',
    'Oklahoma',
    'Oregón',
    'Pensilvania',
    'Rhode Island',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Virginia Occidental',
    'Washington',
    'Wisconsin',
    'Wyoming',
    'Distrito de Columbia',
  ],
  CA: [
    'Alberta',
    'Columbia Británica',
    'Isla del Príncipe Eduardo',
    'Manitoba',
    'Nueva Escocia',
    'Nuevo Brunswick',
    'Nunavut',
    'Ontario',
    'Quebec',
    'Saskatchewan',
    'Terranova y Labrador',
    'Territorios del Noroeste',
    'Yukón',
  ],
  AR: [
    'Buenos Aires',
    'Catamarca',
    'Chaco',
    'Chubut',
    'Ciudad Autónoma de Buenos Aires',
    'Córdoba',
    'Corrientes',
    'Entre Ríos',
    'Formosa',
    'Jujuy',
    'La Pampa',
    'La Rioja',
    'Mendoza',
    'Misiones',
    'Neuquén',
    'Río Negro',
    'Salta',
    'San Juan',
    'San Luis',
    'Santa Cruz',
    'Santa Fe',
    'Santiago del Estero',
    'Tierra del Fuego',
    'Tucumán',
  ],
  CO: [
    'Amazonas',
    'Antioquia',
    'Arauca',
    'Atlántico',
    'Bogotá, D.C.',
    'Bolívar',
    'Boyacá',
    'Caldas',
    'Caquetá',
    'Casanare',
    'Cauca',
    'Cesar',
    'Chocó',
    'Córdoba',
    'Cundinamarca',
    'Guainía',
    'Guaviare',
    'Huila',
    'La Guajira',
    'Magdalena',
    'Meta',
    'Nariño',
    'Norte de Santander',
    'Putumayo',
    'Quindío',
    'Risaralda',
    'San Andrés y Providencia',
    'Santander',
    'Sucre',
    'Tolima',
    'Valle del Cauca',
    'Vaupés',
    'Vichada',
  ],
  ES: [
    'Andalucía',
    'Aragón',
    'Asturias',
    'Cantabria',
    'Castilla-La Mancha',
    'Castilla y León',
    'Cataluña',
    'Comunidad de Madrid',
    'Comunidad Valenciana',
    'Extremadura',
    'Galicia',
    'Islas Baleares',
    'Islas Canarias',
    'La Rioja',
    'Navarra',
    'País Vasco',
    'Región de Murcia',
    'Ceuta',
    'Melilla',
  ],
};

export const CODIGO_TELEFONO_POR_PAIS: Record<string, string> = {
  MX: '+52',
  US: '+1',
  CA: '+1',
  AR: '+54',
  CO: '+57',
  ES: '+34',
};

export function estadosDe(pais: string) {
  return ESTADOS_POR_PAIS[pais] ?? [];
}

export function codigoTelefonoDe(pais: string) {
  return CODIGO_TELEFONO_POR_PAIS[pais] ?? '';
}
